### ISSUE TITLE
Zigbeegerät mit 2 unterschiedlichen State Datenpunkten

### ISSUE THREAD

**Issue by jb2304** [o0shojo0o/AlexaNodeRedImporter_Script#2]
Hallo,
ich habe ein Zigbee Schaltmodul, welches 2 Ausgänge schalten kann. Diese heissen als Datenpunke state_l1 und state_l2. Diese werden von deinem Script natürlich nicht angesprochen, da dort für Zigbee nur "state" als An/Aus Datenpunkt definiert ist. Das dunktioniert auch für alle Geräte die nur einen Schaltausgang haben. Gibt eine Möglichgkeit auch Zigbee Geräte mit mehr als nur "state" zu schalten?

Ich würde auch gerne 2 unterschiedliche Alexa Befehle für die beiden Schaltausgänge definieren.
Ich habe nur keine Idee wie ich das machen soll.

Danke und Grüße

**Comment by o0shojo0o** [comment]
Sorry ich nutze kein Alexa mehr und das Script ist nicht mehr in der Weiterentwicklung und dient nun mehr als Basis. 
Ich habe da leider kein Tipp für Dich,
